### ISSUE TITLE
Add new owner or maintainer to the pypi project

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr-python-client#120]
Hey @felixonmars 

This is a follow-up on the email I sent last week. Would you be willing to add a new owner/maintainer to the [PyPI project](https://pypi.org/project/tldr) for the tldr-python-client, be it someone from the core organization or just a maintainer for this one (e.g. me or @zdroid). We'd ideally like to look to release 1.0.0, but cannot as it seems you're the only one with access to do that.

In a perfect world, I would want to just hook up an automated pipeline to release onto PyPI for any GH release as well to hopefully help alleviate the need for adding tons of people.

cc'ing @zdroid, @sbrl, @agnivade

**Comment by zdroid** [comment]
This client is also becoming increasingly popular, as it already has more stars and weekly views than the node client. With a new official release, that would skyrocket.

**Comment by felixonmars** [comment]
Sorry for the slow response. I actually followed up the last thread (which I seem to added agniva and waldyrious as owners already) but lost track about whom exactly to add next. I'm subscribing to git tags instead of PyPI release for my Arch package so since it's updated there I also got broken memory about someone already released the new version to PyPI so no further action is needed on my side.

I'm fine with adding anyone you mentioned, just please confirm your PyPI username so I can continue. In the mean time I'll work on a release too.

**Comment by felixonmars** [comment]
[1.0.0](https://pypi.org/project/tldr/1.0.0/) released to PyPI.

**Comment by MasterOdin** [comment]
Thanks! For me, I would just want to see https://pypi.org/user/Master_Odin_Bot/ get added as a maintainer so that I can hook up an automated github workflow to push to pypi from a git tag push.

**Comment by felixonmars** [comment]
Master_Odin_Bot added as maintainer of `tldr` on PyPI. Cheers!

**Comment by zdroid** [comment]
I assume this has been solved. :smile:
