### ISSUE TITLE
ImportError: No module named cli

### ISSUE THREAD

**Issue by wfirooooooo** [tldr-pages/tldr-python-client#14]
Hi, I installed tldr as pip install tldr and pip install tldr.py.
When I used it ,show the errors as follows:

$tldr ssh
Traceback (most recent call last):
  File "/usr/bin/tldr", line 7, in <module>
    from tldr.cli import cli
ImportError: No module named cli

What shoud I install?

**Comment by aint** [comment]
Try to uninstall ```tldr.py```:
```bash
pip uninstall tldr.py
```
It seems this repository no longer supported. But I'm going to fork it and push some improvements like cache and others.

**Comment by felixonmars** [comment]
Actually it is, I am just waiting for the reference client to be decided and implement those features in the same way :)

**Comment by lord63** [comment]
@aint Hi, are you using `tldr.py` ? The command for `tldr.py` is:

    $ tldr find <command>

the error log seem strange. What is your python version?

By the way, I suggest that don't install `tldr` and `tldr.py` at the same time, because the main command for `tldr` and `tldr.py` are the same: `tldr`, and may cause problem.
