### ISSUE TITLE
An error occurred with `tldr -r` or `tldr --render`

### ISSUE THREAD

**Issue by witt-bit** [tldr-pages/tldr-python-client#262]
I wrote `pages/common/gendesk.md` and learned from `tldr -h` that the `-r` or `--render` option can preview this md file, but in fact it always fails. Is there something wrong with the way I use it?

![Image](https://github.com/user-attachments/assets/f02c9620-809b-4e23-9ba1-441924007282)

![Image](https://github.com/user-attachments/assets/a9930335-cf67-4dff-9e44-8d2975647b99)

**Comment by acuteenvy** [comment]
I've transferred this issue to the client's repository - please report issues with the client you're using to the appropriate repo.

This is a bug which was fixed in #257, but there hasn't been a release since then. You'll unfortunately have to use a different client for now if you want `--render` to work properly.
