### ISSUE TITLE
Grey color instead of white

### ISSUE THREAD

**Issue by romagnolid** [tldr-pages/tldr-python-client#78]
I tried to set the output of `tldr` to white but it shows a grey color instead.

Default:
![Selection_001](https://user-images.githubusercontent.com/10038298/55784057-09ff9700-5ab0-11e9-9e53-911380b44ca2.png)

`export TLDR_COLOR_EXAMPLE="white"`
![Selection_002](https://user-images.githubusercontent.com/10038298/55784104-2a2f5600-5ab0-11e9-947f-d031384f4baa.png)

I bet it's a problem related to my system (not  a bug), I'm just wondering what's the cause.

**Comment by felixonmars** [comment]
You may want the bold variant "white bold" instead.

**Comment by romagnolid** [comment]
It works but only when `Show bold text in bright colors` is checked in the terminal preferences. 
It still bugs me why doesn't work by default.

**Comment by felixonmars** [comment]
Because tldr client didn't specify a bright style.

**Comment by romagnolid** [comment]
Sorry, I don't understand why not having a bright style specified causes this behaviour.
To be more clear, it bugs me that in order to have a white ouput it needs to be bold too.
I'd rather have, e.g., a white bold name and a white normal description.

p.s. Setting to "grey" shows black instead. I really don't get the logic. Is it an issue related to my system?

**Comment by felixonmars** [comment]
It has something to do with your terminal emulator. Different implementations vary a lot on this topic.

**Comment by zdroid** [comment]
You have to change your own terminal's color palette, which is just utilized by CLI programs such as tldr client. Here is how to do it on Ubuntu:

![Screenshot from 2020-02-04 21-59-56](https://user-images.githubusercontent.com/2725611/73786499-b5917a80-4799-11ea-9b45-330d9ab0fa53.png)

You are supposed to change the rightmost line. Since this isn't an issue with the client iself, I'm closing it.
